import { Rubik } from "next/font/google";
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import "~/styles/globals.css";
import Navigation from "~/components/Navigation";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const rubik = Rubik({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${rubik.className} bg-zinc-50`}>
      <body className="w-full">
        <Navigation />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
